version: '3.1'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: auth.radassist.ai
      KC_HOSTNAME_STRICT: 'true'
      KC_PROXY: edge
    ports:
      - "7777:8080"
    command: ["start-dev"]
